ApplysAleksander
ScienceSpir-it/ApplyForJriOSDev pull request #1
Opened 2016-10-01 09:45 UTC by sAleksander

2016-10-03 06:10 UTC, badeleux requested changes

2016-10-03 06:10 UTC, badeleux commented on README.md
> +My name is Aleksander and Im from poland. Im a self learning programmer who knows c++/c# and Im eager to learn different programming languages. I dont have troubles with using english but if its poss
Great! Nice to know something about you ;)

2016-10-03 06:10 UTC, badeleux commented on README.md
> +Source code:
Please format it properly, best if you could attach it in another file.

2016-10-03 06:10 UTC, badeleux commented on README.md
> +- [x] I know `Swift`/`Objective-C`
How good you know this languages? Are you able to write task nr 3 in one of them?

2016-10-03 19:29 UTC, sAleksander commented on README.md
> +- [x] I know `Swift`/`Objective-C`
In case of those 2 I`m a very begginer. Now I`m not able to write the same prorgam in swift or objective C. However ,it isnt because of lacking programming skills. It`s because i dont know syntax of swift or objective c but it wouldnt be a problem to learn it. Actually the main purpose of why i want to take up this job is to learn.

2016-10-03 19:36 UTC, sAleksander commented on README.md
> +Source code:
-- [+] I know `Swift`/`Objective-C` (very begginer)
-- [-] I've got OS X on my machine
-- [-] I've got device with iOS (if its necessary i think i can manage to buy iphone/ipod in near future)

2016-10-06 19:00 UTC, sAleksander commented
In case of both swift/objective c Im a very begginer. Now Im not able to
write the same prorgam in swift or objective C. However ,it isnt because of
lacking programming skills. It`s because i dont know syntax of swift or
objective c but it wont be a problem to learn it. Actually the main purpose
of why i want to take up this job is to learn and gain expirience.

2016-10-03 8:10 GMT+02:00 Kamil Badyla <notifications@github.com>:

> *@badeleux* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>
> :
>
> >
> -####Hope you came here to apply for iOS Junior Developer Position.
> +My name is Aleksander and Im from poland. Im a self learning programmer who knows c++/c# and Im eager to learn different programming languages. I dont have troubles with using english but if its possible I would prefer to work in polish.
>
> Great! Nice to know something about you ;)
> ------------------------------
>
> In README.md
> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>
> :
>
> >
> -- [ ] I know what's `git` `push`/`commit`/`pull`
> -- [ ] I know `Swift`/`Objective-C`
> -- [ ] I've got OS X on my machine
> -- [ ] I've got device with iOS
> +Source code:
>
> Please format it properly, best if you could attach it in another file.
> ------------------------------
>
> In README.md
> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>
> :
>
> >
> -### 1. Task
> -_Fork_ this repository
> +- [x] I know `Swift`/`Objective-C`
>
> How good you know this languages? Are you able to write task nr 3 in one
> of them?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVg07yVmR1wNbPvRui7vajsZ9EsaKPywks5qwJxHgaJpZM4KLtz5>
> .
>

2016-10-06 19:02 UTC, sAleksander commented
-- [+] I know Swift/Objective-C (very begginer)
-- [-] I've got OS X on my machine
-- [-] I've got device with iOS (if its necessary i think i can manage to
buy iphone/ipod touch in near future)

2016-10-06 21:00 GMT+02:00 Aleksander Szulc <szulcalek@gmail.com>:

> In case of both swift/objective c Im a very begginer. Now Im not able to
> write the same prorgam in swift or objective C. However ,it isnt because of
> lacking programming skills. It`s because i dont know syntax of swift or
> objective c but it wont be a problem to learn it. Actually the main purpose
> of why i want to take up this job is to learn and gain expirience.
>
> 2016-10-03 8:10 GMT+02:00 Kamil Badyla <notifications@github.com>:
>
>> *@badeleux* requested changes on this pull request.
>> ------------------------------
>>
>> In README.md
>> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>
>> :
>>
>> >
>> -####Hope you came here to apply for iOS Junior Developer Position.
>> +My name is Aleksander and Im from poland. Im a self learning programmer who knows c++/c# and Im eager to learn different programming languages. I dont have troubles with using english but if its possible I would prefer to work in polish.
>>
>> Great! Nice to know something about you ;)
>> ------------------------------
>>
>> In README.md
>> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>
>> :
>>
>> >
>> -- [ ] I know what's `git` `push`/`commit`/`pull`
>> -- [ ] I know `Swift`/`Objective-C`
>> -- [ ] I've got OS X on my machine
>> -- [ ] I've got device with iOS
>> +Source code:
>>
>> Please format it properly, best if you could attach it in another file.
>> ------------------------------
>>
>> In README.md
>> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>
>> :
>>
>> >
>> -### 1. Task
>> -_Fork_ this repository
>> +- [x] I know `Swift`/`Objective-C`
>>
>> How good you know this languages? Are you able to write task nr 3 in one
>> of them?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ScienceSpir-it/ApplyForJriOSDev/pull/1#pullrequestreview-2470672>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AVg07yVmR1wNbPvRui7vajsZ9EsaKPywks5qwJxHgaJpZM4KLtz5>
>> .
>>
>
>

2018-09-22 17:49 UTC, closed without merging